# 1- Load dataset

In [1]:
from sklearn.datasets import fetch_20newsgroups

In [2]:
train =fetch_20newsgroups(subset='train')

In [3]:
print(train.keys())

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [4]:
train.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [5]:
c=['comp.graphics','rec.motorcycles','talk.politics.guns']

In [6]:
train =fetch_20newsgroups(subset='train',categories=c)

test = fetch_20newsgroups(subset='test',categories=c)

In [7]:
train.filenames.shape

(1728,)

In [8]:
train.target.shape

(1728,)

In [9]:
test.filenames.shape

(1151,)

In [10]:
set(train.target)

{0, 1, 2}

In [11]:
train.data[5]

"From: ricardo@rchland.vnet.ibm.com (Ricardo Hernandez Muchado)\nSubject: Re: Newsgroup Split\nDisclaimer: This posting represents the poster's views, not necessarily those of IBM\nNntp-Posting-Host: rs43873.rchland.ibm.com\nOrganization: IBM Rochester\nLines: 21\n\nIn article <1quvdoINN3e7@srvr1.engin.umich.edu>, tdawson@engin.umich.edu (Chris Herringshaw) writes:\n|> Concerning the proposed newsgroup split, I personally am not in favor of\n|> doing this.  I learn an awful lot about all aspects of graphics by reading\n|> this group, from code to hardware to algorithms.  I just think making 5\n|> different groups out of this is a wate, and will only result in a few posts\n|> a week per group.  I kind of like the convenience of having one big forum\n|> for discussing all aspects of graphics.  Anyone else feel this way?\n|> Just curious.\n|> \n|> \n|> Daemon\n|> \n\n   I agree with you.\n\n--------------------------------------\nRaist  New A1200 owner   320<->1280 in x, 200<->600 in y\ni

In [12]:
import numpy as np

In [13]:
xtrain , ytrain = np.array(train.data) , np.array(train.target)

xtest , ytest = np.array(test.data) , np.array(test.target)

In [14]:
xtrain.shape

(1728,)

In [15]:
xtrain.ndim

1

In [16]:
xtest.shape

(1151,)

In [17]:
xtest.ndim

1

# 2- Feature Extraction 

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

import pandas as pd

vect=CountVectorizer()

In [19]:
cv_train = vect.fit_transform(xtrain).toarray()
cv_train

array([[2, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
cv_test = vect.transform(xtest).toarray()
cv_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

cv_test.shape

In [21]:
cv_train.shape


(1728, 31652)

In [23]:
cv_train.ndim



2

In [24]:
cv_test.ndim

2

# 3- Naive_Bayes Algorithm

In [25]:
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import confusion_matrix,recall_score,precision_score

nb = MultinomialNB()



In [26]:
nb.fit(cv_train,ytrain)


MultinomialNB()

In [27]:
train_score=nb.score(cv_train,ytrain)
train_score

0.9988425925925926

In [28]:
test_score = nb.score(cv_test,ytest)
test_score

0.9817549956559514

In [29]:
pred = nb.predict(cv_test)

In [30]:
np.bincount(ytest)

array([389, 398, 364], dtype=int64)

In [31]:
confusion_matrix(ytest,pred)

array([[377,   3,   9],
       [  1, 396,   1],
       [  1,   6, 357]], dtype=int64)

In [32]:
print("Precision Score : ",precision_score(ytest,pred,average='weighted'))

Precision Score :  0.9819153162260787


In [33]:

print("Recall Score :" , recall_score(ytest, pred, average='weighted'))

Recall Score : 0.9817549956559514


In [34]:
from sklearn.metrics import accuracy_score 

accuracy_score(ytest,pred)

0.9817549956559514

### testing new texts

In [35]:
new_test1=['My laptop graphics not working']

In [36]:
t1=vect.transform(new_test1)

In [37]:
t1.shape

(1, 31652)

In [38]:
nb.predict(t1)           # 'comp.graphics'     = 0
                         #'rec.motorcycles'    = 1
                         #'talk.politics.guns' = 2

array([0], dtype=int64)

In [39]:
new_test2=['Government can not allow weapon in country']

In [40]:
t2=vect.transform(new_test2)

In [41]:
t2.shape

(1, 31652)

In [42]:
nb.predict(t2)                   # 'comp.graphics'     = 0
                                 #'rec.motorcycles'    = 1
                                 #'talk.politics.guns' = 2

array([2], dtype=int64)

In [43]:
new_test3=['do you have a motor bike']

In [44]:
t3=vect.transform(new_test3)

In [45]:
t3.shape

(1, 31652)

In [46]:
nb.predict(t3)                   # 'comp.graphics'     = 0
                                 #'rec.motorcycles'    = 1
                                 #'talk.politics.guns' = 2

array([1], dtype=int64)